apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-server
  labels:
    {{- include "app.labels" . | nindent 4 }}
    component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    component: server