apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-server
  labels:
    {{- include "app.labels" . | nindent 4 }}
    component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      component: server
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        component: server
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/server-secret.yaml") . | sha256sum }}
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}-server:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.targetPort }}
              protocol: TCP
          {{- if .Values.server.env }}
          {{- $hasConfig := and .Values.server.env.config (kindIs "map" .Values.server.env.config) (gt (len .Values.server.env.config) 0) }}
          {{- $hasSecrets := and .Values.server.env.secrets (kindIs "map" .Values.server.env.secrets) (gt (len .Values.server.env.secrets) 0) }}
          {{- if or $hasConfig $hasSecrets }}
          envFrom:
            {{- if $hasConfig }}
            - configMapRef:
                name: {{ include "app.fullname" . }}-server-config
            {{- end }}
            {{- if $hasSecrets }}
            - secretRef:
                name: {{ include "app.fullname" . }}-server-secret
            {{- end }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
