openapi: 3.0.1
info:
  title: Trajectoires pro
  description: Documentation de l'API  Trajectoires Pro
  license:
    name: MIT License
    url: https://raw.githubusercontent.com/mission-apprentissage/trajectoires-pro/main/LICENSE
  version: 1.0.0

paths:
  /api/inserjeunes/certifications:
    get:
      description: Rechercher des statistiques de certifications
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/millesimes"
        - $ref: "#/components/parameters/code_certifications"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/items_par_page"
      responses:
        200:
          $ref: "#/components/responses/CertificationsResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/certifications.{ext}:
    get:
      description: Exporter des statistiques de certifications
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/millesimes"
        - $ref: "#/components/parameters/code_certifications"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/items_par_page"
        - $ref: "#/components/parameters/ext"
      responses:
        200:
          $ref: "#/components/responses/CertificationsResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/certifications/{code_certification}:
    get:
      description: Obtenir les statistiques d'une certification
      parameters:
        - $ref: "#/components/parameters/code_certification"
        - $ref: "#/components/parameters/millesime"
        - $ref: "#/components/parameters/cfd"
      responses:
        200:
          $ref: "#/components/responses/CertificationResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/certifications/{code_certification}.svg:
    get:
      description: Génère une image SVG (widget) avec les statistiques d'une certification
      parameters:
        - $ref: "#/components/parameters/code_certification"
        - $ref: "#/components/parameters/millesime"
        - $ref: "#/components/parameters/vue"
        - $ref: "#/components/parameters/direction"
        - $ref: "#/components/parameters/theme"
      responses:
        200:
          $ref: "#/components/responses/SVGResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/regionales:
    get:
      description: Rechercher des statistiques régionales
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/millesimes"
        - $ref: "#/components/parameters/code_certifications"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/items_par_page"
      responses:
        200:
          $ref: "#/components/responses/CertificationsResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/regionales.{ext}:
    get:
      description: Exporter des statistiques régionales
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/millesimes"
        - $ref: "#/components/parameters/code_certifications"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/items_par_page"
        - $ref: "#/components/parameters/ext"
      responses:
        200:
          $ref: "#/components/responses/CertificationsResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/regionales/{code_region}:
    get:
      description: Rechercher des statistiques d'une région
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/code_region"
        - $ref: "#/components/parameters/millesimes"
        - $ref: "#/components/parameters/code_certifications"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/items_par_page"
      responses:
        200:
          $ref: "#/components/responses/CertificationsResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/regionales/{code_region}.{ext}:
    get:
      description: Exporter des statistiques d'une région
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/code_region"
        - $ref: "#/components/parameters/millesimes"
        - $ref: "#/components/parameters/code_certifications"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/items_par_page"
        - $ref: "#/components/parameters/ext"
      responses:
        200:
          $ref: "#/components/responses/CertificationsResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/regionales/{code_region}/certifications/{code_certification}:
    get:
      description: Obtenir les statistiques d'une certification
      parameters:
        - $ref: "#/components/parameters/code_region"
        - $ref: "#/components/parameters/code_certification"
        - $ref: "#/components/parameters/millesime"
        - $ref: "#/components/parameters/vue"
      responses:
        200:
          $ref: "#/components/responses/CertificationResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/regionales/{code_region}/certifications/{code_certification}.svg:
    get:
      description: Génère une image SVG (widget) avec les statistiques d'une certification
      parameters:
        - $ref: "#/components/parameters/code_region"
        - $ref: "#/components/parameters/code_certification"
        - $ref: "#/components/parameters/millesime"
        - $ref: "#/components/parameters/vue"
        - $ref: "#/components/parameters/direction"
        - $ref: "#/components/parameters/theme"
      responses:
        200:
          $ref: "#/components/responses/SVGResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/formations:
    get:
      description: Rechercher des statistiques de formations
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/uais"
        - $ref: "#/components/parameters/millesimes"
        - $ref: "#/components/parameters/code_certifications"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/items_par_page"
      responses:
        200:
          $ref: "#/components/responses/FormationsResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/formations.{ext}:
    get:
      description: Exporter des statistiques de formations
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ext"
        - $ref: "#/components/parameters/uais"
        - $ref: "#/components/parameters/millesimes"
        - $ref: "#/components/parameters/code_certifications"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/items_par_page"
      responses:
        200:
          $ref: "#/components/responses/FormationsResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/formations/{uai}-{code_certification}:
    get:
      description: Obtenir des statistiques d'une formation
      parameters:
        - $ref: "#/components/parameters/uai"
        - $ref: "#/components/parameters/code_certification"
        - $ref: "#/components/parameters/millesime"
      responses:
        200:
          $ref: "#/components/responses/FormationResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

  /api/inserjeunes/formations/{uai}-{code_certification}.svg:
    get:
      description: Génère une image SVG (widget) avec les statistiques d'une formation
      parameters:
        - $ref: "#/components/parameters/uai"
        - $ref: "#/components/parameters/code_certification"
        - $ref: "#/components/parameters/millesime"
        - $ref: "#/components/parameters/direction"
        - $ref: "#/components/parameters/theme"
      responses:
        200:
          $ref: "#/components/responses/SVGResponse"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"

components:
  parameters:
    # Query parameters
    millesimes:
      name: millesimes
      in: query
      description: |
        Permet de filtrer la recherche avec un ou plusieurs millesimes séparés par des virgules.

        * Les millesimes des certifications sont des années (ex: 2020)
        * Les millesimes des formations sont des périodes (ex: 2020_2021)
      schema:
        type: string

    code_certifications:
      name: code_certifications
      in: query
      description: |
        Permet de filtrer la recherche avec un ou plusieurs codes de certification séparés par des virgules ou des |.

        Un code certification peut-être un code formation diplome (CFD) ou un code MEF STATS 11
      schema:
        type: string

    uais:
      name: uais
      in: query
      description: Permet de filtrer la recherche avec une ou plusieurs UAI séparées par des virgules.
      schema:
        type: string
        pattern: "^[0-9]{7}[A-Z]{1}$"

    page:
      name: page
      in: query
      description: Le numéro de la page désirée
      schema:
        type: integer

    items_par_page:
      name: items_par_page
      in: query
      description: Le nombre maximum d'éléments dans la page
      schema:
        type: integer
        default: 10

    millesime:
      name: millesime
      in: query
      required: false
      schema:
        type: string

    vue:
      name: vue
      in: query
      description: Retourne les statistiques transformées pour une vue (cfd)
      required: false
      schema:
        type: boolean

    direction:
      name: direction
      in: query
      required: false
      schema:
        type: string
        enum: ["vertical", "horizontal"]
        default: "vertical"

    theme:
      name: theme
      in: query
      required: false
      schema:
        type: string
        enum: ["dsfr", "onisep"]
        default: "dsfr"

    # Path parameters
    uai:
      name: uai
      in: path
      required: true
      schema:
        type: string
        pattern: "^[0-9]{7}[A-Z]{1}$"
        example: "0060033D"

    code_region:
      name: code_region
      description: |
       Le code d'une région

        ```
        84 Auvergne-Rhône-Alpes
        27 Bourgogne-Franche-Comté
        53 Bretagne
        24 Centre-Val de Loire
        00 Collectivités d'outre-mer
        94 Corse
        44 Grand Est
        01 Guadeloupe
        03 Guyane
        32 Hauts-de-France
        04 La Réunion
        02 Martinique
        06 Mayotte
        28 Normandie
        75 Nouvelle-Aquitaine
        76 Occitanie
        52 Pays de la Loire
        93 Provence-Alpes-Côte d'Azur
        11 Île-de-France
        ```
      in: path
      required: true
      schema:
        type: string

    code_certification:
      name: code_certification
      description: Un code certification peut-être un code formation diplome (CFD) ou un code MEF STATS 11
      in: path
      required: true
      schema:
        type: string
        example: "32221031409"

    multiple_codes_certifications:
      name: codes_certifications
      required: true
      in: path
      description: |
        Plusieurs codes de certification séparés par des virgules ou des |.

        Un code certification peut-être un code formation diplome (CFD) ou un code MEF STATS 11
      schema:
        type: string
        example: "32221031409|32221033001|23110022133|01033410|44633521"

    ext:
      name: ext
      in: path
      required: true
      schema:
        type: string
        enum: ["json", "csv"]
        default: json

  schemas:
    Error:
      type: object
      properties:
        statusCode:
          type: integer
        error:
          type: string
        message:
          type: string
    Pagination:
      type: object
      properties:
        page:
          type: string
        resultats_par_page:
          type: number
        nombre_de_page:
          type: number
        total:
          type: number
      description: Statut de la pagination
    Certification:
      type: object
      properties:
        millesime:
          type: string
        code_certification:
          type: string
        filiere:
          type: string
          enum: ["apprentissage", "pro"]
        nb_annee_term:
          type: number
        nb_poursuite_etudes:
          type: number
        nb_en_emploi_12_mois:
          type: number
        nb_en_emploi_6_mois:
          type: number
        nb_sortant:
          type: number
        taux_poursuite_etudes:
          type: number
        taux_emploi_12_mois:
          type: number
        taux_emploi_6_mois:
          type: number
        taux_rupture_contrats:
          type: number
        _meta:
          type: object
          required:
            - date_import
          properties:
            date_import:
              type: string
            title:
              type: string
            description:
              type: string

    Formation:
      type: object
      properties:
        uai:
          type: string
        millesime:
          type: string
        code_certification:
          type: string
        filiere:
          type: string
          enum: ["apprentissage", "pro"]
        nb_annee_term:
          type: number
        nb_poursuite_etudes:
          type: number
        nb_en_emploi_12_mois:
          type: number
        nb_en_emploi_6_mois:
          type: number
        nb_sortant:
          type: number
        taux_poursuite_etudes:
          type: number
        taux_emploi_12_mois:
          type: number
        taux_emploi_6_mois:
          type: number
        _meta:
          type: object
          required:
            - date_import
          properties:
            date_import:
              type: string
            title:
              type: string
            description:
              type: string

  responses:
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    401:
      description: L'api key est manquante ou invalide
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    CertificationsResponse:
      description: La liste des certifications avec leurs statistiques
      content:
        "*/*":
          schema:
            type: object
            properties:
              organismes:
                type: array
                items:
                  $ref: "#/components/schemas/Certification"
              meta:
                type: object
                properties:
                  pagination:
                    $ref: "#/components/schemas/Pagination"
                description: Informations complémentaires

    FormationsResponse:
      description: La liste des formations avec leurs statistiques
      content:
        "*/*":
          schema:
            type: object
            properties:
              organismes:
                type: array
                items:
                  $ref: "#/components/schemas/Formation"
              meta:
                type: object
                properties:
                  pagination:
                    $ref: "#/components/schemas/Pagination"
                description: Informations complémentaires

    FormationResponse:
      description: Une formation avec ses statistiques
      content:
        "*/*":
          schema:
            $ref: "#/components/schemas/Formation"

    CertificationResponse:
      description: Une certification avec ses statistiques
      content:
        "*/*":
          schema:
            $ref: "#/components/schemas/Certification"

    FilieresResponse:
      description: Statistiques aggrégées par filière pour une ou plusieurs certifications
      content:
        "*/*":
          schema:
            type: object
            properties:
              pro: 
                $ref: "#/components/schemas/Certification"
              apprentissage: 
                $ref: "#/components/schemas/Certification"

    SVGResponse:
      description: Une image SVG
      content:
        "image/svg+xml":
          schema:
            type: string
            format: xml

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: apiKey
