/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> yarn doc
 */
import { ObjectId } from "mongodb";

export interface Cfd {
  _id?: ObjectId;
  code_formation: string;
  code_formation_alternatifs: array;
  libelle: string;
  mef?: string;
  mef_stats_9?: string;
  mef_stats_11?: string;
  diplome?: {
    code: string;
    libelle: string;
  };
  _meta: {
    date_import: Date;
  };
}
