/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> make types
 */
import { ObjectId } from "mongodb";

export const name = "codeFormationDiplomes";

export interface CodeFormationDiplomes {
  _id?: ObjectId;
  code_formation: string;
  libelle: string;
  code_formation_alternatifs: array;
  mef: array;
  mef_stats_9: array;
  mef_stats_11: array;
  diplome?: {
    code: string;
    libelle: string;
  };
  _meta: {
    date_import: Date;
  };
}
