/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> yarn doc
 */
import { ObjectId } from "mongodb";

export interface CodesFormations {
  _id?: ObjectId;
  code_formation: string;
  niveau?: {
    code: string;
    diplome: string;
  };
  _meta: {
    date_import: Date;
  };
}
