/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> make types
 */
import { ObjectId } from "mongodb";

export const name = "consumptions";

export interface Consumptions {
  _id?: ObjectId;
  time: Date;
  consumer: string;
  url: string;
  extension?: string;
  uai?: string;
  code_certication?: string;
  v?: number;
}
