/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> yarn doc
 */
const { ObjectId } = require("mongodb");

export interface InserJeunesNationals {
  _id?: ObjectId;
  millesime: string;
  type: "apprentissage" | "pro";
  code_formation: string;
  type_de_diplome: string;
  libelle_de_la_formation: string;
  duree_de_formation?: number;
  diplome_renove_ou_nouveau: string;
  taux_de_poursuite_etudes?: number;
  nb_en_poursuite_etudes?: number;
  nb_en_annee_terminale?: number;
  taux_emploi_6_mois_apres_la_sortie?: number;
  nb_en_emploi_6_mois_apres_la_sortie?: number;
  nb_sortants_6_mois_apres_la_sortie?: number;
  taux_emploi_12_mois_apres_la_sortie?: number;
  nb_en_emploi_12_mois_apres_la_sortie?: number;
}
