/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> yarn doc
 */
import { ObjectId } from "mongodb";

export interface Logs {
  _id?: ObjectId;
  name?: string;
  hostname?: string;
  pid?: number;
  level?: number;
  msg?: string;
  time: Date;
  v?: number;
}
