- name: Install ipset packages
  apt:
    name: [ 'ipset' ]

- name: Add cron to blacklist IPs from daily list
  ansible.builtin.cron:
    name: "blacklist_ips"
    minute: "0"
    hour: "4"
    job: "bash /opt/trajectoires-pro/tools/blacklist-ips.sh >> /var/log/cron.log 2>&1"

