- name: Check if SSL certificate has been generated
  stat: path=/opt/trajectoires-pro/data/ssl/privkey.pem
  register: ssl

- name: Generate SSL certificate with LetsEncrypt
  shell: "bash /opt/trajectoires-pro/tools/ssl/generate-certificate.sh {{dns_name}} {{dns_name_alternative}}"
  register: output
  when: ssl.stat.exists == False

- debug:
    var: output
  when: ssl.stat.exists == True

- name: Add cron to ensure SSL certificate will be renewed
  ansible.builtin.cron:
    name: "renew-certificate"
    minute: "0"
    hour: "2"
    weekday: "1"
    job: "bash /opt/trajectoires-pro/tools/ssl/renew-certificate.sh {{dns_name}} {{dns_name_alternative}} >> /var/log/cron.log 2>&1"
