services:
  reverse_proxy:
    mem_limit: 1g

  server:
    mem_limit: 4g
    logging:
      driver: journald
      options:
        tag: "server"
        labels: "service"
    environment:
      - TRAJECTOIRES_PRO_ENV=production
      - TRAJECTOIRES_PRO_LOG_LEVEL=info
      - TRAJECTOIRES_PRO_LOG_DESTINATIONS=stdout,mongodb,slack
      - TRAJECTOIRES_PRO_PUBLIC_URL=https://api.exposition.inserjeunes.beta.gouv.fr
      - TRAJECTOIRES_PRO_MONGODB_URI={{ vault.TRAJECTOIRES_PRO_MONGODB_URI }}
      - TRAJECTOIRES_PRO_SLACK_WEBHOOK_URL={{ vault.TRAJECTOIRES_PRO_SLACK_WEBHOOK_URL }}
      - TRAJECTOIRES_PRO_INSERJEUNES_USERNAME={{ vault.TRAJECTOIRES_PRO_INSERJEUNES_USERNAME }}
      - TRAJECTOIRES_PRO_INSERJEUNES_PASSWORD={{ vault.TRAJECTOIRES_PRO_INSERJEUNES_PASSWORD }}
      - TRAJECTOIRES_PRO_API_KEY={{ vault.TRAJECTOIRES_PRO_API_KEY }}
      - TRAJECTOIRES_PRO_AUTH_JWT_SECRET={{ vault.TRAJECTOIRES_PRO_PRODUCTION_AUTH_JWT_SECRET }}
      - CATALOGUE_APPRENTISSAGE_USERNAME={{ vault.CATALOGUE_APPRENTISSAGE_USERNAME }}
      - CATALOGUE_APPRENTISSAGE_PASSWORD={{ vault.CATALOGUE_APPRENTISSAGE_PASSWORD }}

  metabase:
    mem_limit: 2g
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_CONNECTION_URI={{ vault.TRAJECTOIRE_PRO_POSTGRESQL_METABASE }}
      - MB_SITE_URL=https://exposition.inserjeunes.beta.gouv.fr/metabase

  mongodb:
    mem_limit: 256m
