/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> make types
 */
import { ObjectId } from "mongodb";

export const name = "mefs";

export interface Mefs {
  _id?: ObjectId;
  mef: string;
  mef_stat_9: string;
  mef_stat_11: string;
  libelle: string;
  code_formation_diplome: string;
  date_fermeture?: Date;
  diplome?: {
    code: string;
    libelle: string;
  };
  _meta: {
    date_import: Date;
  };
}
