/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> make types
 */
import { ObjectId } from "mongodb";

export const name = "migrations";

export interface Migrations {
  _id?: ObjectId;
  version: number;
}
