import { v4 } from "uuid";
process.env.TRAJECTOIRES_PRO_OVH_STORAGE_URI = "https://ovh.com";
process.env.TRAJECTOIRES_PRO_INSERJEUNES_USERNAME = "test";
process.env.TRAJECTOIRES_PRO_INSERJEUNES_PASSWORD = v4();
process.env.TRAJECTOIRES_PRO_API_KEY = v4();
process.env.TRAJECTOIRES_PRO_MILLESIMES = "2018,2019,2020";
process.env.TRAJECTOIRES_PRO_MILLESIMES_FORMATIONS = "2017_2018,2018_2019";
