import { v4 } from "uuid";
process.env.TRAJECTOIRES_PRO_OVH_STORAGE_URI = "https://ovh.com";
process.env.TRAJECTOIRES_PRO_INSERJEUNES_USERNAME = "test";
process.env.TRAJECTOIRES_PRO_INSERJEUNES_PASSWORD = v4();
process.env.TRAJECTOIRES_PRO_API_KEY = v4();
process.env.TRAJECTOIRES_PRO_MILLESIMES = "2018,2019,2020";
process.env.TRAJECTOIRES_PRO_MILLESIMES_FORMATIONS = "2017_2018,2018_2019";
process.env.DIAGORIENTE_CLIENT_ID = "id";
process.env.DIAGORIENTE_CLIENT_SECRET = "secret";
process.env.OMOGEN_API_BASE_PATH = "https://omogen-api-tst-pr.phm.education.gouv.fr";
process.env.OMOGEN_API_KEY = "key";
