---
title: "Base InserJeunes"
subtitle: "Formations couvertes par la base InserJeunes"
output: 
    html_document:
      toc: true
      toc_float:
        toc_collapsed: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,error = FALSE,message = FALSE)

source("../prepa_data_init.R")

```

## Onisep

**Catalogue Onisep V20240515**: [Lien vers le catalogue](https://drive.google.com/drive/folders/1cPL9B2uvz2bn2j2I6bXPPS2jaXAm_g9_)


### Nombre de formations

```{r}

onisep <- read_csv2("C:/Users/arnau/d-sidd Dropbox/Arnaud milet/0_beta/1- Exposition/0- data/onisep/transfer_7425716_files_efd8604c/relations_etablissement-inserjeunes_etablissement_inserjeunes_20240507_161712.csv")

# onisep <- read_csv2("../../../../../0- data/onisep/transfer_7425716_files_efd8604c/relations_etablissement-inserjeunes_etablissement_inserjeunes_20240507_161712.csv")

onisep_simpli <- onisep %>% 
  filter(`Millesime stats`==2022) %>% 
  select(`UAI Établissement IDEO`,`ID inserJeunes (CFD/MEF)`,Type) %>% 
  setNames(c("UAI","MEFSTAT11","Filiere")) %>% 
  mutate(Filiere=ifelse(Filiere=="app","Apprentissage","Scolaire"))

catalogue_onisep_renseigne <- expo_mef_catalogue_partenaire(catalogue_init = onisep_simpli,type_source = "onisep")
stats_catalogue_onisep <- expo_mef_stats_catalogue_partenaire(catalogue_partenaire_renseigne = catalogue_onisep_renseigne)


stats_catalogue_onisep$stats_catalogue_partenaire %>%
  mutate_all(replace_na,0) %>% 
  mutate_at(vars(4:length(.)),as.numeric) %>% 
  mutate_at(vars(contains("Part ")),scales::percent,accuracy=0.1) %>% 
  kableExtra::kbl(format.args = list(big.mark = " ", decimal.mark = ",")) %>%
  kableExtra::kable_paper()

```


### Nombre d'élèves en année terminale

```{r}
stats_catalogue_onisep$stats_catalogue_partenaire_effectifs_temp %>%
  select(-`Nombre d'élèves à la rentrée`) %>% 
  mutate_all(replace_na,0) %>% 
  mutate_at(vars(4:length(.)),as.numeric) %>% 
    mutate_at(vars(`Part du  catalogue`,`Couverture - Hors familles de métiers`,`Couverture - Familles de métiers`,contains("(%)")),scales::percent,accuracy=0.1) %>% 
  DT::datatable(options = list(dom = 't',pageLength = 10000),rownames = F)

```


