services:
  reverse_proxy:
    ports:
      - 443:443
    volumes:
      - /opt/trajectoires-pro/data/nginx:/data
      - /opt/trajectoires-pro/data/ssl:/ssl:ro
    environment:
      - SERVER_NAME={{dns_name}}
      - SERVER_NAME_ALTERNATIVE={{dns_name_alternative}}
      - NGINX_ALWAYS_TLS_REDIRECT=true
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem

  server:
    volumes:
      - /opt/trajectoires-pro/data/server:/data
    environment:
      - TRAJECTOIRES_PRO_INSERSUP_BASE_URL={{ vault.TRAJECTOIRES_PRO_INSERSUP_BASE_URL }}
      - TRAJECTOIRES_PRO_INSERSUP_API_KEY={{ vault.TRAJECTOIRES_PRO_INSERSUP_API_KEY }}

  mongodb:
    volumes:
      - /opt/trajectoires-pro/data/mongodb/db:/data/db
      - /opt/trajectoires-pro/data/mongodb/configdb:/data/configdb
      - /opt/trajectoires-pro/data/mongodb/backups:/data/backups
      - /opt/trajectoires-pro/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  metabase:
    volumes:
      - /opt/trajectoires-pro/data/metabase:/data
    environment:
      - MB_DB_FILE=/data/metabase.db
