services:
  server:
    environment:
      - TRAJECTOIRES_PRO_ENV=recette
      - TRAJECTOIRES_PRO_LOG_LEVEL=info
      - TRAJECTOIRES_PRO_LOG_DESTINATIONS=stdout,mongodb
      - TRAJECTOIRES_PRO_PUBLIC_URL=https://api.{{ dns_name }}
      - TRAJECTOIRES_PRO_MONGODB_URI=mongodb://trajectoires-pro:{{ vault.TRAJECTOIRES_PRO_MONGODB_USER_PASSWORD }}@mongodb:27017/trajectoires-pro?authSource=admin&retryWrites=true&w=majority
      - TRAJECTOIRES_PRO_INSERJEUNES_USERNAME={{ vault.TRAJECTOIRES_PRO_INSERJEUNES_USERNAME }}
      - TRAJECTOIRES_PRO_INSERJEUNES_PASSWORD={{ vault.TRAJECTOIRES_PRO_INSERJEUNES_PASSWORD }}
      - TRAJECTOIRES_PRO_API_KEY={{ vault.TRAJECTOIRES_PRO_API_KEY }}
      - TRAJECTOIRES_PRO_AUTH_JWT_SECRET={{ vault.TRAJECTOIRES_PRO_RECETTE_AUTH_JWT_SECRET }}
      - CATALOGUE_APPRENTISSAGE_USERNAME={{ vault.CATALOGUE_APPRENTISSAGE_USERNAME }}
      - CATALOGUE_APPRENTISSAGE_PASSWORD={{ vault.CATALOGUE_APPRENTISSAGE_PASSWORD }}

  ui:
    environment:
      - METABASE_SITE_URL=https://exposition.inserjeunes.beta.gouv.fr/metabase
      - METABASE_DASHBOARD_STATS_ID=53
      - METABASE_DASHBOARD_STATS_DETAILS_ID=47
      - METABASE_DASHBOARD_STATS_REGION_ID=58
    build:
      args:
        - METABASE_SITE_URL=https://exposition.inserjeunes.beta.gouv.fr/metabase
        - METABASE_DASHBOARD_STATS_ID=53
        - METABASE_DASHBOARD_STATS_DETAILS_ID=47
        - METABASE_DASHBOARD_STATS_REGION_ID=58

  metabase:
    environment:
      - MB_SITE_URL=https://{{ dns_name }}/metabase
