---
title: "Base InserJeunes"
subtitle: "Formations couvertes par la base InserJeunes"
output: 
    html_document:
      toc: true
      toc_float:
        toc_collapsed: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,error = FALSE,message = FALSE)

source("../prepa_data_init.R")

```

## Affelnet

**Catalogue Affelnet 2024 V20240531_Extraction_catalogue_SLA_2024**: [Lien vers le catalogue](https://docs.google.com/spreadsheets/d/1i3URB63eaiQJ9UfteY4_PULom_I5f1wK/edit#gid=397487575)

### Nombre de formations


```{r}
### 20240531 - Extraction catalogue SLA 2024----
Affelnet_20240531_Extraction_catalogue_SLA_2024  <- read_excel(file.path(chemin_racine_data,"affelnet/2024/20240531 - Catalogue offres voie professionnelle - AFFELNET.xlsx") ) 


affelnet_simpli  <- Affelnet_20240531_Extraction_catalogue_SLA_2024 %>% 
  filter(!Académie%in% c("Polynesie","Nvelle-Caledonie"),`Visible portail`=="O") %>% 
  select(Etablissement,MEF,Statut) %>% 
  setNames(c("UAI","MEFSTAT11","Filiere")) %>% 
  mutate(Filiere=ifelse(Filiere=="AP","Apprentissage","Scolaire")) 


catalogue_affelnet_SLA_2024_renseigne <- expo_mef_catalogue_partenaire(catalogue_init = affelnet_simpli,type_source = "affelnet")
stats_catalogue_affelnet_SLA_2024 <- expo_mef_stats_catalogue_partenaire(catalogue_partenaire_renseigne = catalogue_affelnet_SLA_2024_renseigne)



stats_catalogue_affelnet_SLA_2024$stats_catalogue_partenaire %>%
  mutate_all(replace_na,0) %>% 
  mutate_at(vars(4:length(.)),as.numeric) %>% 
    mutate_at(vars(`Part du  catalogue`,`Couverture - Hors familles de métiers`,`Couverture - Familles de métiers`,contains("(%)")),scales::percent,accuracy=0.1) %>% 
  DT::datatable(options = list(dom = 't',pageLength = 10000),rownames = F)
  # kableExtra::kbl(format.args = list(big.mark = " ", decimal.mark = ",")) %>%
  # kableExtra::kable_paper()
```

### Nombre d'élèves en année terminale

```{r}
stats_catalogue_affelnet_SLA_2024$stats_catalogue_partenaire_effectifs_temp %>%
  select(-`Nombre d'élèves à la rentrée`) %>% 
  mutate_all(replace_na,0) %>% 
  mutate_at(vars(4:length(.)),as.numeric) %>% 
    mutate_at(vars(`Part du  catalogue`,`Couverture - Hors familles de métiers`,`Couverture - Familles de métiers`,contains("(%)")),scales::percent,accuracy=0.1) %>% 
  DT::datatable(options = list(dom = 't',pageLength = 10000),rownames = F)

```


