---
title: "Base InserJeunes"
subtitle: "Formations couvertes par la base InserJeunes"
output: 
    html_document:
      toc: true
      toc_float:
        toc_collapsed: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,error = FALSE,message = FALSE)

source("../prepa_data_init.R")


```

## Affelnet

**Catalogue Affelnet 2023 V20240112_Extraction_catalogue_SLA_2023**: [Lien vers le catalogue](https://docs.google.com/spreadsheets/d/100miT_jBPQuXo-rA0HnGWX0v2W84Po9m/edit?usp=drive_link&ouid=107607241761816962784&rtpof=true&sd=true)

### Nombre de formations

```{r}
Affelnet_20240112_Extraction_catalogue_SLA_2023 <- read_excel(file.path(chemin_racine_data,"affelnet/2023/20240112 - Extraction catalogue SLA 2023.xlsx"),
                                                      skip = 2)

affelnet_simpli <- Affelnet_20240112_Extraction_catalogue_SLA_2023 %>% 
  select(Etablissement,MEFSTAT11,Statut) %>% 
  setNames(c("UAI","MEFSTAT11","Filiere")) %>% 
  mutate(Filiere=ifelse(Filiere=="AP","Apprentissage","Scolaire"))

catalogue_affelnet_SLA_2023_renseigne <- expo_mef_catalogue_partenaire(catalogue_init = affelnet_simpli,type_source = "affelnet")
stats_catalogue_affelnet_SLA_2023 <- expo_mef_stats_catalogue_partenaire(catalogue_partenaire_renseigne = catalogue_affelnet_SLA_2023_renseigne)

stats_catalogue_affelnet_SLA_2023$stats_catalogue_partenaire %>%
  mutate_all(replace_na,0) %>% 
  mutate_at(vars(4:length(.)),as.numeric) %>% 
    mutate_at(vars(`Part du  catalogue`,contains("(%)")),scales::percent,accuracy=0.1) %>% 
  DT::datatable(options = list(dom = 't',pageLength = 10000),rownames = F)
  # kableExtra::kbl(format.args = list(big.mark = " ", decimal.mark = ",")) %>%
  # kableExtra::kable_paper()

```


<!--

### Nombre d'élèves en année terminale

```{r}
stats_catalogue_affelnet_SLA_2023$stats_catalogue_partenaire_effectifs_temp %>%
  select(-`Nombre d'élèves à la rentrée`) %>% 
  mutate_all(replace_na,0) %>% 
  mutate_at(vars(4:length(.)),as.numeric) %>% 
    mutate_at(vars(`Part du  catalogue`,contains("(%)")),scales::percent,accuracy=0.1) %>% 
  DT::datatable(options = list(dom = 't',pageLength = 10000),rownames = F)

```

-->

### Nombre de voeux émis

```{r}
stats_catalogue_affelnet_SLA_2023$stats_catalogue_partenaire_voeux %>%
  mutate_all(replace_na,0) %>% 
  mutate_at(vars(4:length(.)),as.numeric) %>% 
    mutate_at(vars(`Part du  catalogue`,contains("(%)")),scales::percent,accuracy=0.1) %>% 
  DT::datatable(options = list(dom = 't',pageLength = 10000),rownames = F)

```

