---
title: "Base InserJeunes"
subtitle: "Formations couvertes par la base InserJeunes"
output: 
    html_document:
      toc: true
      toc_float:
        toc_collapsed: true

params: 
    phase: "Production"
    date_maj: format(Sys.time(), '%d/%m/%Y')
    emplacement_data_meta_formationsStats_init: "Donnees IJ/metabase/production/FormationsStats.csv"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	error = FALSE,
	message = FALSE,
	warning = FALSE
)
# Chargement des librairies ----
library(tidyverse)
library(readxl)
library(jsonlite)
library(knitr)
library(kableExtra)

chemin_racine_data <- "../../../../0- data" 

# Données ----
## Données BCN ----
n_mef <- read_csv2(file.path(chemin_racine_data,"n_mef_.csv"))
n_formation_diplome <- read_delim(file.path(chemin_racine_data,"BCN/n_formation_diplome_.csv"),delim = ";", escape_double = FALSE, trim_ws = TRUE)
n_niveau_formation_diplome <- read_csv2(file.path(chemin_racine_data,"BCN/n_niveau_formation_diplome_.csv"))

## Données IJ pour analyse de la couverture ----
### Etablissements ----
data_meta_formationsStats_init <- read_csv(file.path(chemin_racine_data,params$emplacement_data_meta_formationsStats_init))

data_meta_formationsStats_init <- data_meta_formationsStats_init %>%
  setNames(names(.) %>%
             str_to_lower() %>%
             str_replace_all(" ", "_"))


data_meta_formationsStats_init <- data_meta_formationsStats_init %>%
  bind_cols(  str_split_fixed(
    data_meta_formationsStats_init$donnee_source,
    pattern = ",",
    n = 2
  ) %>%
    as_tibble() %>%
    mutate(
      V1 = str_remove(V1, "\\{:code_certification "),
      V2 = str_remove(V2, " :type "),
      V2 = str_remove(V2, "\\}")
    ) %>%  
    setNames(c(
      "code_certification_source", "type_source"
    ))) %>% 
  bind_cols(
    str_split_fixed(
      data_meta_formationsStats_init$diplome,
      pattern = ",",
      n = 2
    )%>%
      as_tibble() %>%
      mutate(
        V1 = str_remove(V1, "\\{:code "),
        # V1 = str_remove(V1, "\""),
        V2 = str_remove(V2, " :libelle "),
        V2 = str_remove(V2, "\\}")
      ) %>%
      setNames(c(
        "niveau_diplome", "libelle_type_diplome"
      ))
  ) %>% 
  mutate(
    "Couverture Taux En Emploi 6 Mois" = ifelse(is.na(taux_en_emploi_6_mois), F, T),
    "Couverture Taux Autres 6 Mois" = ifelse(is.na(taux_autres_6_mois), F, T),
    "Couverture Taux En poursuite" = ifelse(is.na(taux_en_formation), F, T)
  ) %>%
  distinct(
    code_certification ,
    code_formation_diplome,
    uai,
    type_source,
    filiere,
    millesime,
    niveau_diplome,
    libelle_type_diplome,
    nb_annee_term,
    nb_en_emploi_6_mois,
    nb_poursuite_etudes,
    taux_en_emploi_6_mois,
    taux_autres_6_mois,
    taux_en_formation,
    `Couverture Taux En Emploi 6 Mois`,
    `Couverture Taux Autres 6 Mois`,
    `Couverture Taux En poursuite`
  ) %>%
  mutate(presence_ij = T,
         Avant_apres_continuum = case_when(
           nb_annee_term < 20 ~ "Sous le seuil de 20 élèves",
           type_source %in% c("self","nouvelle") ~ "Avant continuum",
           type_source == "ancienne" ~ "Apres continuum"
         ),
         millesime=str_sub(millesime,-4),
         Couverture=case_when(
           millesime == max(millesime) & str_detect(Avant_apres_continuum, "continuum") ~ "Couvert",
           Avant_apres_continuum =="Avant continuum" ~ "Couvert",
           Avant_apres_continuum =="Apres continuum" ~ "Non couvert",
           T~Avant_apres_continuum
         )
  )  %>%
  left_join(n_formation_diplome %>%
              select(FORMATION_DIPLOME,NIVEAU_FORMATION_DIPLOME),
            by=c("code_formation_diplome" ="FORMATION_DIPLOME")
  ) %>%
  left_join(
    n_niveau_formation_diplome %>%
      select(NIVEAU_FORMATION_DIPLOME,NIVEAU_QUALIFICATION_RNCP),
    by="NIVEAU_FORMATION_DIPLOME"
  ) %>%
  mutate(id_unique=1:n()) 


stats_InserJeunes <- data_meta_formationsStats_init %>% 
  filter(type_source%in%c("self","ancienne"),millesime==2022) %>% 
  mutate(
    type_formation=case_when(
      niveau_diplome%in%0:4 ~ "Avant le bac",
      niveau_diplome%in%5:8 ~ "Après le bac"
    ),
    type_formation=factor(type_formation,levels=c("Avant le bac","Après le bac")),
    libelle_type_diplome=case_when(
      str_detect(libelle_type_diplome,"DIP3-CNAM")~"Titre professionnel homologué",
      str_detect(libelle_type_diplome,"TH3")~"Titre professionnel homologué",
      str_detect(libelle_type_diplome,"TH4")~"Titre professionnel homologué",
      str_detect(libelle_type_diplome,"TH5")~"Titre professionnel homologué",
      # str_detect(libelle_type_diplome,"DIV-2")~"Autres diplômes",
      # str_detect(libelle_type_diplome,"DIV-3")~"Autres diplômes",
      # str_detect(libelle_type_diplome,"DIV-4")~"Autres diplômes",
      # str_detect(libelle_type_diplome,"DIV-5")~"Autres diplômes",
      str_detect(libelle_type_diplome,"BPA")~"BPA",
      str_detect(libelle_type_diplome,"CSA")~"CSA",
      str_detect(libelle_type_diplome,"CS")~"CS",
      str_detect(libelle_type_diplome,"ASSIMI.BTS")~"BTS",
      libelle_type_diplome=="LIC LMD"~"Licence générale",
      libelle_type_diplome=="LIC PRO"~"Licence professionnelle",
      libelle_type_diplome=="MAST ENS"~"Master MEEF",
      libelle_type_diplome=="MAST LMD"~"Master LMD",
      T~libelle_type_diplome
    ),
    filiere=case_when(
      filiere=="pro"~"Scolaire",
      filiere=="superieur"~"Supérieur",
      filiere=="apprentissage"~"Apprentissage"
      )
  )  %>% 
  # filter(libelle_type_diplome!="Autres diplômes") %>% 
  group_by(niveau_diplome,type_formation,libelle_type_diplome,filiere) %>% 
  summarise(presence=n()) %>% 
  mutate(filiere=str_to_title(filiere)) %>% 
  pivot_wider(names_from = filiere,values_from = presence) %>% 
  mutate_all(replace_na,0) %>%   
  rename(
    "Niveau diplôme"=niveau_diplome,
    "Avant/après bac"=type_formation,
    "Type diplôme"=libelle_type_diplome
  ) %>% 
  ungroup() %>% 
  mutate(
    Volume=Scolaire + Apprentissage + `Supérieur`,
    "Part base"=prop.table(Volume),
    Base="InserJeunes"
  ) 


```


## Base InserJeunes - `r params$phase`

*Dernière mise à jour : `r params$date_maj`* 


```{r}
stats_InserJeunes %>% 
  bind_rows(
    stats_InserJeunes %>% 
  summarise_if(is.numeric,sum) %>% 
  mutate(
    `Niveau diplôme`="Total",
    `Avant/après bac`="Total",
    `Type diplôme`="Total",
    Base="Total"
  ) 
  ) %>% 
  mutate(`Part base`=scales::percent(`Part base`,accuracy=0.1)) %>%
  kbl(format.args = list(big.mark = " ", decimal.mark = ",")) %>%
  kable_paper()
```

