// TODO: move in API
const niveauFormationDiplomes = [
  { niveauFormationDiplome: "967", libelleCourt: "BAFD", libelleLong: "BREVET D'APTITUDE AUX FONCTIONS DE DIRECTEUR" },
  { niveauFormationDiplome: "966", libelleCourt: "BAFA", libelleLong: "BREVET D'APTITUDE AUX FONCTIONS D'ANIMATEUR" },
  { niveauFormationDiplome: "56S", libelleCourt: "TH5-S", libelleLong: "TH DE NIV 5 SANTE SOCIAL" },
  {
    niveauFormationDiplome: "16A",
    libelleCourt: "TH1-A",
    libelleLong: "TH DE NIV 1 DES ORGANISMES ET CHAMBRES D'AGRICULTURE",
  },
  { niveauFormationDiplome: "265", libelleCourt: "DIP GVL", libelleLong: "DIPLOME GRADE ET VISE LICENCE" },
  { niveauFormationDiplome: "964", libelleCourt: "BIMER", libelleLong: "BREVET D'INITIATION A LA MER" },
  {
    niveauFormationDiplome: "965",
    libelleCourt: "CAEIMER",
    libelleLong: "CERTIFICAT D'APTITUDE A L'ENSEIGNEMENT D'INITIATION A LA MER",
  },
  { niveauFormationDiplome: "251", libelleCourt: "BUT", libelleLong: "BACHELOR UNIVERSITAIRE DE TECHNOLOGIE" },
  { niveauFormationDiplome: "56X", libelleCourt: "TH5-X", libelleLong: "TH DE NIV 5 ORGANISMES GESTIONNAIRES DIVERS" },
  { niveauFormationDiplome: "56T", libelleCourt: "TH5-T", libelleLong: "TH DE NIV 5 MINISTERE DU TRAVAIL - AFPA" },
  { niveauFormationDiplome: "56M", libelleCourt: "TH5-M", libelleLong: "TH DE NIV 5 DES CHAMBRES DE METIERS" },
  {
    niveauFormationDiplome: "56J",
    libelleCourt: "TH5-J",
    libelleLong: "TH DE NIV 5 MINISTERE DE LA JEUNESSE ET DES SPORTS",
  },
  { niveauFormationDiplome: "46X", libelleCourt: "TH4-X", libelleLong: "TH DE NIV 4 ORGANISMES GESTIONNAIRES DIVERS" },
  { niveauFormationDiplome: "56R", libelleCourt: "TH5-R", libelleLong: "TH DE NIV 5 INSTANCES REGIONALES" },
  {
    niveauFormationDiplome: "56Q",
    libelleCourt: "TH5-Q",
    libelleLong: "TH DE NIV 5 MINISTERE DE L'EQUIPEMENT TRANSPORT TOURISME",
  },
  { niveauFormationDiplome: "56N", libelleCourt: "TH5-N", libelleLong: "TH DE NIV 5 MINISTERE INDUSTRIE" },
  { niveauFormationDiplome: "56E", libelleCourt: "TH5-E", libelleLong: "TH DE NIV 5 EDUCATION RECTORAT GRETA ..." },
  {
    niveauFormationDiplome: "56D",
    libelleCourt: "TH5-D",
    libelleLong: "TH DE NIV 5 DES ARMEES - MINISTERE DE LA DEFENSE",
  },
  { niveauFormationDiplome: "5ZZ", libelleCourt: "TNH5", libelleLong: "TITRE DE NIV 5 NON HOMOLOGUE - CQP...." },
  { niveauFormationDiplome: "56Z", libelleCourt: "TH5", libelleLong: "TH DE NIV 5 NON PRECISE" },
  {
    niveauFormationDiplome: "56C",
    libelleCourt: "TH5-C",
    libelleLong: "TH DE NIV 5 DES CCI ET MINISTERE COMMERCE ARTISANAT PME",
  },
  {
    niveauFormationDiplome: "56A",
    libelleCourt: "TH5-A",
    libelleLong: "TH DE NIV 5 DES ORGANISMES ET CHAMBRES D'AGRICULTURE",
  },
  { niveauFormationDiplome: "4ZZ", libelleCourt: "TNH4", libelleLong: "TITRE DE NIV 4  NON HOMOLOGUE - CQP...." },
  { niveauFormationDiplome: "46Z", libelleCourt: "TH4", libelleLong: "TH DE NIV 4 NON PRECISE" },
  { niveauFormationDiplome: "46U", libelleCourt: "TH4-U", libelleLong: "TH DE NIV 4 MENRT EDUCATION  UNIVERSITES" },
  { niveauFormationDiplome: "46T", libelleCourt: "TH4-T", libelleLong: "TH DE NIV 4 MINISTERE DU TRAVAIL - AFPA" },
  { niveauFormationDiplome: "46S", libelleCourt: "TH4-S", libelleLong: "TH DE NIV 4 SANTE SOCIAL" },
  { niveauFormationDiplome: "46R", libelleCourt: "TH4-R", libelleLong: "TH DE NIV 4 INSTANCES REGIONALES" },
  {
    niveauFormationDiplome: "46Q",
    libelleCourt: "TH4-Q",
    libelleLong: "TH DE NIV 4 MINISTERE DE L'EQUIPEMENT TRANSPORT TOURISME",
  },
  { niveauFormationDiplome: "46N", libelleCourt: "TH4-N", libelleLong: "TH DE NIV 4 MINISTERE INDUSTRIE" },
  { niveauFormationDiplome: "46M", libelleCourt: "TH4-M", libelleLong: "TH DE NIV 4 DES CHAMBRES DE METIERS" },
  { niveauFormationDiplome: "46K", libelleCourt: "TH4-K", libelleLong: "TH DE NIV 4 MINISTERE DE LA CULTURE" },
  {
    niveauFormationDiplome: "46J",
    libelleCourt: "TH4-J",
    libelleLong: "TH DE NIV 4 MINISTERE DE LA JEUNESSE ET DES SPORTS",
  },
  { niveauFormationDiplome: "46E", libelleCourt: "TH4-E", libelleLong: "TH DE NIV 4 EDUCATION RECTORAT GRETA ..." },
  {
    niveauFormationDiplome: "46D",
    libelleCourt: "TH4-D",
    libelleLong: "TH DE NIV 4 DES ARMEES - MINISTERE DE LA DEFENSE",
  },
  {
    niveauFormationDiplome: "46C",
    libelleCourt: "TH4-C",
    libelleLong: "TH DE NIV 4 DES CCI ET MINISTERE COMMERCE ARTISANAT PME",
  },
  {
    niveauFormationDiplome: "46A",
    libelleCourt: "TH4-A",
    libelleLong: "TH DE NIV 4 DES ORGANISMES ET CHAMBRES D'AGRICULTURE",
  },
  { niveauFormationDiplome: "36Z", libelleCourt: "TH3", libelleLong: "TH DE NIV 3 NON PRECISE" },
  { niveauFormationDiplome: "36X", libelleCourt: "TH3-X", libelleLong: "TH DE NIV 3 ORGANISMES GESTIONNAIRES DIVERS" },
  { niveauFormationDiplome: "161", libelleCourt: "MASTERE", libelleLong: "MASTERE" },
  { niveauFormationDiplome: "36U", libelleCourt: "TH3-U", libelleLong: "TH DE NIV 3 MENRT EDUCATION  UNIVERSITES" },
  { niveauFormationDiplome: "36T", libelleCourt: "TH3-T", libelleLong: "TH DE NIV 3 MINISTERE DU TRAVAIL - AFPA" },
  { niveauFormationDiplome: "36S", libelleCourt: "TH3-S", libelleLong: "TH DE NIV 3 SANTE SOCIAL" },
  { niveauFormationDiplome: "36R", libelleCourt: "TH3-R", libelleLong: "TH DE NIV 3 INSTANCES REGIONALES" },
  {
    niveauFormationDiplome: "36Q",
    libelleCourt: "TH3-Q",
    libelleLong: "TH DE NIV 3 MINISTERE DE L'EQUIPEMENT TRANSPORT TOURISME",
  },
  { niveauFormationDiplome: "36N", libelleCourt: "TH3-N", libelleLong: "TH DE NIV 3 MINISTERE INDUSTRIE" },
  { niveauFormationDiplome: "36M", libelleCourt: "TH3-M", libelleLong: "TH DE NIV 3 DES CHAMBRES DE METIERS" },
  { niveauFormationDiplome: "36K", libelleCourt: "TH3-K", libelleLong: "TH DE NIV 3 MINISTERE DE LA CULTURE" },
  {
    niveauFormationDiplome: "36J",
    libelleCourt: "TH3-J",
    libelleLong: "TH DE NIV 3 MINISTERE DE LA JEUNESSE ET DES SPORTS",
  },
  { niveauFormationDiplome: "36E", libelleCourt: "TH3-E", libelleLong: "TH DE NIV 3 EDUCATION RECTORAT GRETA ..." },
  {
    niveauFormationDiplome: "36D",
    libelleCourt: "TH3-D",
    libelleLong: "TH DE NIV 3 DES ARMEES - MINISTERE DE LA DEFENSE",
  },
  {
    niveauFormationDiplome: "36C",
    libelleCourt: "TH3-C",
    libelleLong: "TH DE NIV 3 DES CCI ET MINISTERE COMMERCE ARTISANAT PME",
  },
  {
    niveauFormationDiplome: "36A",
    libelleCourt: "TH3-A",
    libelleLong: "TH DE NIV 3 DES ORGANISMES ET CHAMBRES D'AGRICULTURE",
  },
  { niveauFormationDiplome: "299", libelleCourt: "AUTRE N-2", libelleLong: "AUTRES FORMATIONS DE NIVEAU 2" },
  { niveauFormationDiplome: "26Z", libelleCourt: "TH2", libelleLong: "TH  DE NIV 2 NON PRECISE" },
  { niveauFormationDiplome: "26X", libelleCourt: "TH2-X", libelleLong: "TH DE NIV 2 ORGANISMES GESTIONNAIRES DIVERS" },
  { niveauFormationDiplome: "26U", libelleCourt: "TH2-U", libelleLong: "TH DE NIV 2 MENRT EDUCATION  UNIVERSITES" },
  { niveauFormationDiplome: "26T", libelleCourt: "TH2-T", libelleLong: "TH DE NIV 2 MINISTERE DU TRAVAIL - AFPA" },
  { niveauFormationDiplome: "26S", libelleCourt: "TH2-S", libelleLong: "TH DE NIV 2 SANTE SOCIAL" },
  { niveauFormationDiplome: "26R", libelleCourt: "TH2-R", libelleLong: "TH DE NIV 2 INSTANCES REGIONALES" },
  {
    niveauFormationDiplome: "26Q",
    libelleCourt: "TH2-Q",
    libelleLong: "TH DE NIV 2 MINISTERE DE L'EQUIPEMENT TRANSPORT TOURISME",
  },
  { niveauFormationDiplome: "26N", libelleCourt: "TH2-N", libelleLong: "TH DE NIV 2 MINISTERE INDUSTRIE" },
  { niveauFormationDiplome: "26M", libelleCourt: "TH2-M", libelleLong: "TH DE NIV 2 DES CHAMBRES DE METIERS" },
  { niveauFormationDiplome: "26K", libelleCourt: "TH2-K", libelleLong: "TH DE NIV 2 MINISTERE DE LA CULTURE" },
  {
    niveauFormationDiplome: "26J",
    libelleCourt: "TH2-J",
    libelleLong: "TH DE NIV 2 MINISTERE DE LA JEUNESSE ET DES SPORTS",
  },
  { niveauFormationDiplome: "26E", libelleCourt: "TH2-E", libelleLong: "TH DE NIV 2 EDUCATION RECTORAT GRETA ..." },
  {
    niveauFormationDiplome: "26D",
    libelleCourt: "TH2-D",
    libelleLong: "TH DE NIV 2 DES ARMEES - MINISTERE DE LA DEFENSE",
  },
  {
    niveauFormationDiplome: "26C",
    libelleCourt: "TH2-C",
    libelleLong: "TH DE NIV 2 DES CCI ET MINISTERE COMMERCE ARTISANAT PME",
  },
  {
    niveauFormationDiplome: "26A",
    libelleCourt: "TH2-A",
    libelleLong: "TH DE NIV 2 DES ORGANISMES ET CHAMBRES D'AGRICULTURE",
  },
  {
    niveauFormationDiplome: "16J",
    libelleCourt: "TH1-J",
    libelleLong: "TH DE NIV 1 MINISTERE DE LA JEUNESSE ET DES SPORTS",
  },
  { niveauFormationDiplome: "16N", libelleCourt: "TH1-N", libelleLong: "TH DE NIV 1 MINISTERE INDUSTRIE" },
  {
    niveauFormationDiplome: "16Q",
    libelleCourt: "TH1-Q",
    libelleLong: "TH DE NIV 1 MINISTERE DE L'EQUIPEMENT TRANSPORT TOURISME",
  },
  { niveauFormationDiplome: "16R", libelleCourt: "TH1-R", libelleLong: "TH DE NIV 1 INSTANCES REGIONALES" },
  { niveauFormationDiplome: "16S", libelleCourt: "TH1-S", libelleLong: "TH DE NIV 1 SANTE SOCIAL" },
  { niveauFormationDiplome: "16T", libelleCourt: "TH1-T", libelleLong: "TH DE NIV 1 MINISTERE DU TRAVAIL - AFPA" },
  { niveauFormationDiplome: "16U", libelleCourt: "TH1-U", libelleLong: "TH DE NIV 1 MENRT EDUCATION  UNIVERSITES" },
  { niveauFormationDiplome: "16X", libelleCourt: "TH1-X", libelleLong: "TH DE NIV 1 ORGANISMES GESTIONNAIRES DIVERS" },
  { niveauFormationDiplome: "16Z", libelleCourt: "TH1", libelleLong: "TH DE NIV 1 NON PRECISE" },
  { niveauFormationDiplome: "999", libelleCourt: "INDETERM.", libelleLong: "INDETERMINE" },
  { niveauFormationDiplome: "970", libelleCourt: "ATT PRO", libelleLong: "ATTESTATION POUR DIPLOMES PROFESSIONNELS" },
  { niveauFormationDiplome: "963", libelleCourt: "JDC", libelleLong: "JOURNEE DEFENSE ET CITOYENNETE" },
  { niveauFormationDiplome: "962", libelleCourt: "ASN", libelleLong: "ATTESTATION SAVOIR NAGER" },
  { niveauFormationDiplome: "960", libelleCourt: "BIA", libelleLong: "BREVET D'INITIATION AERONAUTIQUE" },
  { niveauFormationDiplome: "933", libelleCourt: "DILF", libelleLong: "DIPLOME INITIAL DE LANGUE FRANCAISE" },
  { niveauFormationDiplome: "932", libelleCourt: "DELF", libelleLong: "DIPLOME D'ETUDES EN LANGUE FRANCAISE" },
  { niveauFormationDiplome: "931", libelleCourt: "DCL", libelleLong: "DIPLOME DE COMPETENCE EN LANGUES" },
  { niveauFormationDiplome: "930", libelleCourt: "CER LANG", libelleLong: "CERTIFICATION EN LANGUE VIVANTE ETRANGERE" },
  { niveauFormationDiplome: "921", libelleCourt: "C2I", libelleLong: "CERTIFICAT INFORMATIQUE ET INTERNET" },
  { niveauFormationDiplome: "920", libelleCourt: "B2I", libelleLong: "BREVET INFORMATIQUE ET INTERNET" },
  {
    niveauFormationDiplome: "914",
    libelleCourt: "PRAP",
    libelleLong: "PREVENTION DES RISQUES LIES A L'ACTIVITE PHYSIQUE",
  },
  { niveauFormationDiplome: "913", libelleCourt: "APS", libelleLong: "ATTESTATION A PORTER SECOURS" },
  { niveauFormationDiplome: "912", libelleCourt: "SST", libelleLong: "CERTIFICAT SAUVETEUR SECOURISME DU TRAVAIL" },
  { niveauFormationDiplome: "911", libelleCourt: "PSC", libelleLong: "PREVENTION ET SECOURS CIVIQUES" },
  { niveauFormationDiplome: "910", libelleCourt: "AFPS", libelleLong: "ATTESTATION DE FORMATION AUX PREMIERS SECOURS" },
  { niveauFormationDiplome: "900", libelleCourt: "ATT SECUR", libelleLong: "ATTESTATION DE SECURITE ROUTIERE" },
  { niveauFormationDiplome: "700", libelleCourt: "1ER DEGRE", libelleLong: "PREELEMENTAIRE ET ELEMENTAIRE" },
  { niveauFormationDiplome: "699", libelleCourt: "AUT.1E CYC", libelleLong: "AUTRES FORMATIONS DE 1ER CYCLE" },
  { niveauFormationDiplome: "690", libelleCourt: "ENS ADAPTE", libelleLong: "ENSEIGNEMENT ADAPTE" },
  { niveauFormationDiplome: "672", libelleCourt: "CFG", libelleLong: "CERTIFICAT DE FORMATION GENERALE" },
  { niveauFormationDiplome: "671", libelleCourt: "DNB", libelleLong: "DIPLOME NATIONAL DU BREVET" },
  { niveauFormationDiplome: "670", libelleCourt: "1E CYC.GEN", libelleLong: "FORMATIONS GENERALES DE 1ER CYCLE" },
  { niveauFormationDiplome: "641", libelleCourt: "FAJ", libelleLong: "FORMATION D'APPRENTIS JUNIORS" },
  {
    niveauFormationDiplome: "640",
    libelleCourt: "CLIPA",
    libelleLong: "CLASSE D'INITIATION PREPROFESSIONNELLE PAR ALTERNANCE",
  },
  {
    niveauFormationDiplome: "631",
    libelleCourt: "DIMA",
    libelleLong: "DISPOSITIF D'INITIATION AUX METIERS EN ALTERNANCE",
  },
  { niveauFormationDiplome: "630", libelleCourt: "CPA", libelleLong: "CPA" },
  { niveauFormationDiplome: "620", libelleCourt: "CPPN", libelleLong: "CPPN" },
  { niveauFormationDiplome: "610", libelleCourt: "1CYC.TECHN", libelleLong: "ENSEIGNEMENT TECHNOLOGIQUE DE 1ER CYCLE" },
  { niveauFormationDiplome: "599", libelleCourt: "AUTRE N-5", libelleLong: "AUTRES FORMATIONS DE NIVEAU 5" },
  { niveauFormationDiplome: "583", libelleCourt: "CIPPA", libelleLong: "CYCLE D'INSERTION PROF.PAR ALTERNANCE" },
  { niveauFormationDiplome: "582", libelleCourt: "MODAL N-5", libelleLong: "MODULE D'ACTION EN LYCEE DE NIVEAU_5" },
  { niveauFormationDiplome: "581", libelleCourt: "FCIL N-5", libelleLong: "FCIL & FC NON DIPLOMANTE POST NIVEAU_5" },
  { niveauFormationDiplome: "564", libelleCourt: "TH5-AG", libelleLong: "TH DE NIV 5 REMONTES DES CFA AGRICOLES" },
  {
    niveauFormationDiplome: "563",
    libelleCourt: "CSA NIV5",
    libelleLong: "CERTIFICAT DE SPECIALISATION AGRICOLE DE NIVEAU 5",
  },
  {
    niveauFormationDiplome: "562",
    libelleCourt: "CPAP",
    libelleLong: "CERTIFICAT POLYNESIEN D'APTITUDES PROFESSIONNELLES",
  },
  { niveauFormationDiplome: "560", libelleCourt: "DIV-5", libelleLong: "AUTRES DIPLOMES DE NIVEAU V" },
  { niveauFormationDiplome: "553", libelleCourt: "BPA5", libelleLong: "BREVET PROFESSIONNEL AGRICOLE DE NIVEAU V" },
  { niveauFormationDiplome: "550", libelleCourt: "SES 3 A 6", libelleLong: "SES/SEGPA 3EME A 6EME ANNEE" },
  { niveauFormationDiplome: "513", libelleCourt: "BEPA", libelleLong: "BREVET D'ETUDES PROFESSIONNELLES AGRICOLES" },
  { niveauFormationDiplome: "510", libelleCourt: "BEP", libelleLong: "BREVET D'ETUDES PROFESSIONNELLES" },
  {
    niveauFormationDiplome: "968",
    libelleCourt: "BNJ POMPIE",
    libelleLong: "BREVET NATIONAL DE JEUNE SAPEUR-POMPIER ET DE JEUNE MARIN-POMPIER",
  },
  { niveauFormationDiplome: "482", libelleCourt: "MODAL N-4", libelleLong: "MODULE D'ACTION EN LYCEE DE NIVEAU_4" },
  { niveauFormationDiplome: "481", libelleCourt: "FCIL N-4", libelleLong: "FCIL & FC NON DIPLOMANTE POST NIVEAU_4" },
  { niveauFormationDiplome: "464", libelleCourt: "TH4-AG", libelleLong: "TH DE NIV 4 REMONTES DES CFA AGRICOLES" },
  {
    niveauFormationDiplome: "463",
    libelleCourt: "CSA NIV4",
    libelleLong: "CERTIFICAT DE SPECIALISATION AGRICOLE DE NIVEAU 4",
  },
  { niveauFormationDiplome: "460", libelleCourt: "DIV-4", libelleLong: "AUTRES DIPLOMES DE NIVEAU IV" },
  { niveauFormationDiplome: "453", libelleCourt: "BPA4", libelleLong: "BREVET PROFESSIONNEL AGRICOLE DE NIVEAU IV" },
  { niveauFormationDiplome: "450", libelleCourt: "BP", libelleLong: "BREVET PROFESSIONNEL" },
  {
    niveauFormationDiplome: "446",
    libelleCourt: "BP JEPS",
    libelleLong: "BREVET PROFESSIONNEL DE LA JEUNESSE, DE L'EDUCATION POPULAIRE ET DU SPORT",
  },
  { niveauFormationDiplome: "433", libelleCourt: "BAC TEC AG", libelleLong: "BAC TECHNOLOGIQUE AGRICOLE" },
  {
    niveauFormationDiplome: "16C",
    libelleCourt: "TH1-C",
    libelleLong: "TH DE NIV 1 DES CCI ET MINISTERE COMMERCE ARTISANAT PME",
  },
  {
    niveauFormationDiplome: "16D",
    libelleCourt: "TH1-D",
    libelleLong: "TH DE NIV 1 DES ARMEES - MINISTERE DE LA DEFENSE",
  },
  { niveauFormationDiplome: "16E", libelleCourt: "TH1-E", libelleLong: "TH DE NIV 1 EDUCATION RECTORAT GRETA ..." },
  { niveauFormationDiplome: "423", libelleCourt: "BTA", libelleLong: "BREVET DE TECHNICIEN AGRICOLE" },
  { niveauFormationDiplome: "420", libelleCourt: "BT", libelleLong: "BREVET DE TECHNICIEN" },
  { niveauFormationDiplome: "410", libelleCourt: "BEI", libelleLong: "BREVET D'ENSEIGNEMENT INDUSTRIEL" },
  { niveauFormationDiplome: "403", libelleCourt: "BAC PRO AG", libelleLong: "BAC PROFESSIONNEL AGRICOLE" },
  {
    niveauFormationDiplome: "401",
    libelleCourt: "BMA",
    libelleLong: "BREVET DES METIERS D'ART - BREVET DES METIERS DU SPECTACLE",
  },
  { niveauFormationDiplome: "400", libelleCourt: "BAC PRO", libelleLong: "BAC PROFESSIONNEL" },
  { niveauFormationDiplome: "399", libelleCourt: "AUTRE N-3", libelleLong: "AUTRES FORMATIONS DE NIVEAU 3" },
  { niveauFormationDiplome: "382", libelleCourt: "MODAL N-3", libelleLong: "MODULE D'ACTION EN LYCEE DE NIVEAU_3" },
  { niveauFormationDiplome: "381", libelleCourt: "FCIL N-3", libelleLong: "FCIL & FC NON DIPLOMANTE POST NIVEAU_3" },
  { niveauFormationDiplome: "371", libelleCourt: "DECF", libelleLong: "DIPLOME ETUDES COMPTABLES & FINANCIERES" },
  { niveauFormationDiplome: "370", libelleCourt: "CPGE", libelleLong: "CLASSE PREPARATOIRE AUX GRANDES ECOLES" },
  { niveauFormationDiplome: "364", libelleCourt: "TH3-AG", libelleLong: "TH DE NIV 3 REMONTES DES CFA AGRICOLES" },
  {
    niveauFormationDiplome: "363",
    libelleCourt: "CSA NIV3",
    libelleLong: "CERTIFICAT DE SPECIALISATION AGRICOLE DE NIVEAU 3",
  },
  { niveauFormationDiplome: "360", libelleCourt: "DIV-3", libelleLong: "AUTRES DIPLOMES DE NIVEAU III" },
  { niveauFormationDiplome: "356", libelleCourt: "DU-3", libelleLong: "AUTRES DIPLOMES UNIVERSITAIRES DE NIV 3" },
  {
    niveauFormationDiplome: "355",
    libelleCourt: "DEUST",
    libelleLong: "DIPLOME D'ETUDES UNIVERSITAIRES DE SCIENCES ET TECHNOLOGIE",
  },
  { niveauFormationDiplome: "352", libelleCourt: "DEUG", libelleLong: "DIPLOME D'ETUDES UNIVERSITAIRES GENERALES" },
  { niveauFormationDiplome: "350", libelleCourt: "DUT", libelleLong: "DIPLOME UNIVERSITAIRE DE TECHNOLOGIE" },
  { niveauFormationDiplome: "346", libelleCourt: "DIP3-CNAM", libelleLong: "DIPLOMES CNAM DE NIV 3 (DPCE, DPCT ...)" },
  {
    niveauFormationDiplome: "336",
    libelleCourt: "DE JEPS",
    libelleLong: "DIPLOME D'ETAT DE LA JEUNESSE, DE L'EDUCATION POPULAIRE ET DU SPORT",
  },
  { niveauFormationDiplome: "323", libelleCourt: "BTSA", libelleLong: "BREVET DE TECHNICIEN SUPERIEUR AGRICOLE" },
  {
    niveauFormationDiplome: "322",
    libelleCourt: "ASSIMI.BTS",
    libelleLong: "AUTRE DIPL. ASSIMILE AU BTS (DTS-DPECF-DNTS)",
  },
  { niveauFormationDiplome: "321", libelleCourt: "DMA", libelleLong: "DIPLOME DES METIERS D'ART" },
  { niveauFormationDiplome: "320", libelleCourt: "BTS", libelleLong: "BREVET DE TECHNICIEN SUPERIEUR" },
  { niveauFormationDiplome: "264", libelleCourt: "TH2-AG", libelleLong: "TH DE NIV 2 REMONTES DES CFA AGRICOLES" },
  {
    niveauFormationDiplome: "263",
    libelleCourt: "CSA NIV2",
    libelleLong: "CERTIFICAT DE SPECIALISATION AGRICOLE DE NIVEAU 2",
  },
  { niveauFormationDiplome: "260", libelleCourt: "DIV-2", libelleLong: "AUTRES DIPLOMES DE NIVEAU II" },
  { niveauFormationDiplome: "256", libelleCourt: "DU-2", libelleLong: "AUTRES DIPLOMES UNIVERSITAIRES DE NIV 2" },
  {
    niveauFormationDiplome: "255",
    libelleCourt: "GD ETB LIC",
    libelleLong: "DIPLOME GRAND ETABLISSEMENT GRADE LICENCE",
  },
  { niveauFormationDiplome: "250", libelleCourt: "LIC PRO", libelleLong: "LICENCE PROFESSIONNELLE" },
  { niveauFormationDiplome: "246", libelleCourt: "DIP2-CNAM", libelleLong: "DIPLOMES CNAM DE NIV 2 (DESE, DEST ....)" },
  {
    niveauFormationDiplome: "241",
    libelleCourt: "DNMADE",
    libelleLong: "DIPLOME NATIONAL DES METIERS D'ART ET DU DESIGN",
  },
  { niveauFormationDiplome: "240", libelleCourt: "DSAA", libelleLong: "DIPLOME SUPERIEUR DES ARTS APPLIQUES" },
  {
    niveauFormationDiplome: "503",
    libelleCourt: "CAPA",
    libelleLong: "CERTIFICAT D'APTITUDE PROFESSIONNELLE AGRICOLE",
  },
  {
    niveauFormationDiplome: "236",
    libelleCourt: "DES JEPS",
    libelleLong: "DIPLOME D'ETAT SUPERIEUR DE LA JEUNESSE, DE L'EDUCATION POPULAIRE ET DU SPORT",
  },
  { niveauFormationDiplome: "230", libelleCourt: "ING-M", libelleLong: "DIPLOMES D'INGENIEUR-MAITRE" },
  {
    niveauFormationDiplome: "220",
    libelleCourt: "MST",
    libelleLong: "MAITRISES DE SCIENCES ET TECHNIQUES DES UNIVERSITES (YC MIAGE  MSG )",
  },
  { niveauFormationDiplome: "210", libelleCourt: "DNTS-A", libelleLong: "DNTS (DIPL.NAT. TECHNO. SPEC.) ANCIEN CODE" },
  { niveauFormationDiplome: "205", libelleCourt: "LIC LMD", libelleLong: "LICENCE LMD" },
  { niveauFormationDiplome: "201", libelleCourt: "MAIT", libelleLong: "MAITRISE DES UNIVERSITES" },
  { niveauFormationDiplome: "200", libelleCourt: "LIC", libelleLong: "LICENCE DES UNIVERSITES" },
  { niveauFormationDiplome: "145", libelleCourt: "MASTER", libelleLong: "MASTER (LMD) INDIFFERENCIE" },
  { niveauFormationDiplome: "135", libelleCourt: "MASTER PRO", libelleLong: "MASTER PROFESSIONNEL" },
  { niveauFormationDiplome: "125", libelleCourt: "MASTER R", libelleLong: "MASTER RECHERCHE" },
  { niveauFormationDiplome: "100", libelleCourt: "DOCTORAT", libelleLong: "DOCTORAT D'UNIVERSITE" },
  { niveauFormationDiplome: "013", libelleCourt: "MC AG", libelleLong: "MENTION COMPLEMENTAIRE AGRICOLE" },
  { niveauFormationDiplome: "010", libelleCourt: "MC", libelleLong: "MENTION COMPLEMENTAIRE" },
  { niveauFormationDiplome: "170", libelleCourt: "ING", libelleLong: "INGENIEURS RECONNUS (RCT..), NFI , ALTERNANCE" },
  { niveauFormationDiplome: "120", libelleCourt: "DEA", libelleLong: "DIPLOME D'ETUDES APPROFONDIES" },
  { niveauFormationDiplome: "130", libelleCourt: "DESS", libelleLong: "DIPLOMES D'ETUDES SUPERIEURES SPECIALISEES" },
  { niveauFormationDiplome: "131", libelleCourt: "DRT", libelleLong: "DIPLOME DE RECHERCHE TECHNOLOGIQUE" },
  { niveauFormationDiplome: "140", libelleCourt: "DSAA-1", libelleLong: "DIPLOME SUPERIEUR DES ARTS APPLIQUES" },
  { niveauFormationDiplome: "146", libelleCourt: "DIP1-CNAM", libelleLong: "DIPLOMES CNAM DE NIV 1" },
  {
    niveauFormationDiplome: "155",
    libelleCourt: "GD ETB MAS",
    libelleLong: "DIPLOME GRAND ETABLISSEMENT GRADE MASTER",
  },
  { niveauFormationDiplome: "156", libelleCourt: "DU-1", libelleLong: "AUTRES DIPLOMES UNIVERSITAIRES DE NIV 1" },
  { niveauFormationDiplome: "160", libelleCourt: "DIV-1", libelleLong: "AUTRES DIPLOMES DE NIVEAU I" },
  { niveauFormationDiplome: "164", libelleCourt: "TH1-AG", libelleLong: "TH DE NIV 1 REMONTES DES CFA AGRICOLES" },
  { niveauFormationDiplome: "165", libelleCourt: "DIP GVM", libelleLong: "DIPLOME GRADE ET VISE MASTER" },
  { niveauFormationDiplome: "180", libelleCourt: "MBA", libelleLong: "MASTER OF BUSINESS ADMINISTRATION" },
  { niveauFormationDiplome: "199", libelleCourt: "AUTRE N-1", libelleLong: "AUTRES FORMATIONS DE NIVEAU 1" },
  {
    niveauFormationDiplome: "216",
    libelleCourt: "DEM MONT 6",
    libelleLong: "DIPLOME D�ETAT METIERS DE LA MONTAGNE DE NIVEAU 6",
  },
  {
    niveauFormationDiplome: "316",
    libelleCourt: "DEM MONT 5",
    libelleLong: "DIPLOME D�ETAT METIERS DE LA MONTAGNE DE NIVEAU 5",
  },
  {
    niveauFormationDiplome: "326",
    libelleCourt: "CP JEPS 5",
    libelleLong: "CERTIFICAT COMPLEMENTAIRE JEPS DE NIVEAU 5",
  },
  {
    niveauFormationDiplome: "426",
    libelleCourt: "CP JEPS 4",
    libelleLong: "CERTIFICAT COMPLEMENTAIRE JEPS DE NIVEAU 4",
  },
  { niveauFormationDiplome: "206", libelleCourt: "MN SPORT 6", libelleLong: "MISE A NIVEAU SPORTS DE NIVEAU 6" },
  { niveauFormationDiplome: "306", libelleCourt: "MN SPORT 5", libelleLong: "MISE A NIVEAU SPORTS DE NIVEAU 5" },
  { niveauFormationDiplome: "406", libelleCourt: "MN SPORT 4", libelleLong: "MISE A NIVEAU SPORTS DE NIVEAU 4" },
  { niveauFormationDiplome: "500", libelleCourt: "CAP", libelleLong: "CERTIFICAT D'APTITUDE PROFESSIONNELLE" },
  { niveauFormationDiplome: "470", libelleCourt: "BAC GENE", libelleLong: "BAC GENERAL" },
  { niveauFormationDiplome: "430", libelleCourt: "BAC TECHNO", libelleLong: "BAC TECHNOLOGIQUE" },
  {
    niveauFormationDiplome: "901",
    libelleCourt: "PERMIS ETG",
    libelleLong: "PERMIS DE CONDUIRE : EPREUVE THEORIQUE GENERALE",
  },
  { niveauFormationDiplome: "499", libelleCourt: "AUTRE N-4", libelleLong: "AUTRES FORMATIONS DE NIVEAU 4" },
  { niveauFormationDiplome: "461", libelleCourt: "CS 4", libelleLong: "CERTIFICAT DE SPECIALISATION DE NIVEAU 4" },
  { niveauFormationDiplome: "561", libelleCourt: "CS 3", libelleLong: "CERTIFICAT DE SPECIALISATION DE NIVEAU 3" },
];

export function getNiveauFormatonDiplome(niveauFormationDiplome: string) {
  return (
    niveauFormationDiplomes.find((v) => v.niveauFormationDiplome === niveauFormationDiplome) || {
      niveauFormationDiplome: "",
      libelleCourt: "INCONNU",
      libelleLong: "INCONNU",
    }
  );
}
