/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the collection schema file,
 * To regenerate this file run $> make types
 */
import { ObjectId } from "mongodb";

export const name = "cfds";

export interface Cfds {
  _id?: ObjectId;
  code_formation: string;
  libelle: string;
  code_formation_alternatifs: string[];
  date_fermeture?: Date;
  diplome?: {
    code: string;
    libelle: string;
  };
  _meta: {
    date_import: Date;
  };
}
