title: Expo IJ
description: >-
  Éclairer les choix d’orientation des jeunes en exposant des données
  pertinentes relatives aux parcours de formation et à l’insertion professionnelle.

theme: just-the-docs

callouts:
  highlight:
    color: purple
  note:
    color: yellow

aux_links:
  Page beta.gouv:
    - https://beta.gouv.fr/startups/exposition-ij.html
aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Retour en haut de page"