#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -eu

function validate_commit() {
  cd .
  local sensible_files_pattern="\.(csv|xls|xls(x?)|json|env)$"
  local exception="package.json$|tsconfig.json$|server/data/depp(.*).csv$|bcn/n_mef.csv$|server/jsconfig.json$|acce_etablissements.csv$|server/tests/fixtures/files/*.json$|server/public/remixicon/remixicon.*.json$"
  local files
  files=$(git diff --cached --name-only | grep -v -E "$exception" | grep -E "$sensible_files_pattern") || true

  if [ -z "$files" ]; then
    make lint
    make test
  else
    echo
    echo "ERROR: Preventing commit of potentially sensible files:"
    echo
    echo "$files" | sed "s/^/   /"
    echo
    echo "Either reset those files, add them to .gitignore or remove them."
    echo
    echo "If you know what you are doing, please double-check that you are not commiting"
    echo "any credentials, password or sensible data and run git commit again with --no-verify."
    echo
    exit 1
  fi
  cd -
}

validate_commit
