name: Build the application (dev or recette)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Merci de préciser un environnement (ex. dev, recette ou production)'
        required: true
        type: choice
        options:
          - dev
          - recette
          - production
        default: 'dev'
jobs:
  build-dev:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.env_name || 'dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: azure/setup-helm@v4.3.0
        id: install
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Ansible
        shell: bash
        run: |
          # sudo apt-get update
          # sudo apt-get install -y ansible
          #python3 -m pip install --upgrade pip
          pip install ansible-core
          pip install requests
          pip install docker
          pip install kubernetes
          pip install PyYAML
      - name: Create vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass.txt
      - name: Set env
        run: echo "VAULT_PASSWORD_FILE=.vault_pass.txt" >> $GITHUB_ENV
      - name: Build with ansible
        run: |
          bash .infra/scripts/build-app.sh \
            "$ENVIRONMENT" \
            "${{ github.head_ref || github.ref_name }}"