name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: make ci

      # codecov server
      - name: Upload Server coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./server/.coverage
          name: codecov-server
          verbose: true

      # codecov ui
      - name: Upload UI coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./ui/coverage
          name: codecov-ui
          verbose: true
