name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v6
        with:
          node-version: 24.10.0

      - name: Cache MongoDB binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/mongodb-binaries
          key: ${{ runner.os }}-mongodb
            
      - run: make ci
        env:
          MONGOMS_DOWNLOAD_DIR: ~/.cache/mongodb-binaries
          MONGOMS_DOWNLOAD_URL: https://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2404-8.0.15.tgz

      - run: make test
        env:
          MONGOMS_DOWNLOAD_DIR: ~/.cache/mongodb-binaries
          MONGOMS_DOWNLOAD_URL: https://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2404-8.0.15.tgz

      
      

      # codecov server
      - name: Upload Server coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./server/.coverage
          name: codecov-server
          verbose: true
