name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v6
        with:
          node-version: 24.10.0

      - name: Setup MongoDB binary cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/mongodb-binaries
          key: mongodb-${{ runner.os }}-8.0.15

      - name: Download MongoDB binary
        run: |
          npx mongodb-memory-server-core download --version 8.0.15
        working-directory: ./server
        
      - run: make ci

      - run: make test

      # codecov server
      - name: Upload Server coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./server/.coverage
          name: codecov-server
          verbose: true
